# Server Config
server:
  port: 8765

#Eureka  Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Application Config
spring:
  application:
    name: hr-api-gateway
  cloud:
    config:
      import-check:
        enabled: false
  discovery:
    enabled: true
  gateway:
    dicovery:
      locator:
        enabled: true
        lower-case-service-id: true
    routes:
      - id: hr-payroll
        uri: lb://hr-payroll
        predicates:
        - Path=/hr-payroll/**
      - id: hr-worker
        uri: lb://hr-worker
        predicates:
        - Path=/hr-worker/**
      - id: hr-api-gateway
        uri: lb://hr-api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

# Management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: gateway, health