# Application
spring:
 application:
  name: hr-payroll
 mvc:
  pathmatch:
   matching-strategy: ant-path-matcher
 cloud:
  loadbalancer:
   ribbon:
    enabled: false

server:
 port: 8101

#Eureka
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 60000

ribbon:
 ConnectTimeout: 10000
 ReadTimeout: 20000
 