# Server Config
server:
   port: ${PORT:0}

# Application
spring:
   application:
      name: hr-payroll
   config:
      import: optional:configserver:http://localhost:8888/config/hr-payroll
   cloud:
      config:
         profile: dev