# Server Config
server:
   port: ${PORT:0}

# Application
spring:
   application:
      name: hr-payroll
   config:
      import: optional:configserver:http://localhost:8888/
   cloud:
      config:
         profile: prd
   mvc:
      pathmatch:
         matching-strategy: ant-path-matcher

#Eureka
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka


resilience4j:
   retry:
      intances:
         getPayment:
            max-attempts: 5
            wait-duration: 1s

# Spring Docs Config
springdoc:
   api-docs:
      path: hr-payroll/v3/api-docs
 