# Server Config
server:
  port: ${PORT:0}

# Application Config
spring:
  application:
    name: hr-worker
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: default
  datasource:
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
    ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  

#Eureka Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
 
hr-worker:
  greeting: "Hello!"
  default-value: "HR-WORKER microservice information"

# Management Config
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

# Spring Docs Config
springdoc:
  api-docs:
    path: hr-worker/v3/api-docs