# Server Config
server:
  port: 8889

# Application Config
spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Math7Guitar/ms-course-config/
          default-label: main
          username: Math7Guitar
          password: Mza331998
          search-paths:
          - 'config/*'
