# Server Config
server:
 port: 8761

#Application Config
spring:
 application:
  name: hr-eureka-server
 freemarker:
  template-loader-path: classpath:/templates/
  prefer-file-system-access: false


